const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/client/modules/**/components/**/*.{js,ts,jsx,tsx}",
    "./src/@components/**/*.{js,ts,jsx,tsx}",
    "./src/@modules/**/*.{js,ts,jsx,tsx}",
    "./src/client/common/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    screens: {
      'xs': '375px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'sz-1220': '1220px',
      'xl': '1280px',   
      'sz-1336':'1336px',
      'sz-1440':'1440px',
      '2xl': '1536px',
      'sz-1680':'1680px',    
      '3xl': '1920px',
      'sz-2304':'2304px',
      'sz-2560':'2560px',
      'sz-2880':'2880px',
      'sz-3000':'3000px',
    },
    extend: {
      colors: {
        'primary-light': 'red',
        'primary-dark': 'green',

        // Use `super` prefix - this is the new color palette
        super: {
          white: '#FFFFFF',
          'secondary-text': '#6E767D',
          'bg': '#141414',
          'toastr':'#2F73FF',
          'primary-blue': '#5981f3',
          'flyouts': '#242424',
          'destructive': '#E95C5C',
          'scrim': 'rgba(0, 0, 0, 0.5)',
          'textboxes': '#222222',
          frame: '#19171d',
          yellow: '#FFCC4A',
          purple: '#A33CF6',
          toast: '#29A335',
          green: '#82C43C',
          'light-grey':'#BFBFC3',
          'grey-1':'#625F60',
          'greenlight':'#14C063',
          'light-black':'#181818',
          'hover-tag':"#2D2D2D",
          'text-light-green':"#3C8826",
          'text-light-pink':"#EEBBEE",
          'text-light-blue':"#355DFF",
          'text-light-red':"#EEBBBB",
          'back-text-black':"#222429",
          'back-text-light-black':"#6E767D",
          'back-color':'#191919',
          'back-section':'#1f1e23',
          'hover-background':'#1f1e23',
          'back-setup':'#121212',
          'confirmation-popup':'#232529',
          'warning-message':'#FF6475',
          'active-color':'#5CDB8E',
          'penfing-color':'#FF9D61',
          'section-hover-background':'#D9D9D9',
          'border-grey':'#E0E0E0',
          'back-sec':'#E4E4E4',
          'table-text':'#4F4F4F',
          'br-sec':'#EBEFFF',
          'input-border':'#E5EBFF',
          'title':'#828282',
          'bg-light-green':'#98DDB4',
          'text-placeholder':'#D0D0D0',
          'light-pink':'#F8ECFD',
          'dash-light':'#99A2B9',
          'light-orange':'#FBDABF',
          'preview-background':'#FAFBFF',
          'text-dropdown':'#333333',
          'light-blue':'#F5F7FF',
          'placehoder':"#D6DCF0",
          'toastr-green':'#05A763',
          'text-sec-grey':'#8F92A1',
          'lighter-green':'#339966',
          'asscent':'#6C5DD3',
          'place-color':'#B1C7E7',
          'warning':'#E85231',
          'bottom-border':'#D4DCFF',
          'lite-violet':'#CED8FF',
          'border-table':'#F2F2F2',
          'intiated':'#C7BAEC',
          'published':'#21EC64',
          'outofcredit':'#FF8369',
          'loading-para':'#838383',
          'light-pink':'#F0BDD5',
          'color-primary':'#ffffff',
          'color-secondary':'#000000',
          'color-secondary-light':'#231F20',
          'color-secondary-light2':'#263959',
          'color-light-grey':'#73686B',
          'border-light-blue':'#82A9CC',
          'light-text-greeen':'#808191',
          'light-dash-pink':'#FCFAF8',
          'light-brown':'#391400',
          'light-border-blk':'#DFE9FB',
          'caramel':'#FFF0E5',
          'text-light-blk':'#B2B2B2',
          'lighter-grey':'#EBEBEB',
          'text-green':'#3BB95E',
          'bg-light-white':'#FAFAFA',
          'gyp-red':'#ED1D24',
          'gyp-green':'#3A9B14',
          'gyp-yellow':'#FF8A00',
          'gyp-grey':'#fafafa'
        },
        screens: {
          
        },
        // this is the old color palette. Do not use this
        palette: {
          0: '#FFFFFF',
          1: '#E1E7FF',
          2: '#C7D2FF',
          3: '#B0B8C5',
          4: '#667085',
          5: '#475467',
          6: '#344054',
          7: '#1D2939',
          8: '#101828',
          9: '#000000',
          'A': '#3271D8',
          'B': '#014CFD',
          'E': '#5C4E1D',
          'border': '#2C2C2C',
          'logo': '#DBDBDB',
          'body-text': '#B9CDF4',
          'description': '#7C8BA9',
          'yellow-1': '#FFDD57',
          'modal': '#010101',
          'cream-brown':'#F4D2C0'      
        },

        base: {
          '1': '#101728',
          '2': '#1F2839',
          '3': '#2A3547',
        },
        grey: {
          '1': '#909AA1',
          '2': '#6F7B86',
          '3': '#4D5D6B',
        },
        text: {
          '1': '#B6C5EB',
          '2': '#B8CCF1',
          '3': '#D3EFFD',
        },
        blue: {
          'light': '#62BDF3',
          'base': '#4AA7E6',
          'dark': '#3A52EA',
        },
        violet: {
          light: '#8390F1',
          dark: '#5B43EE',
        },
      },
      fontSize: {
        'xxs': '0.625rem',
      },
      fontFamily: {
        'body': ['Nunito Sans', 'sans-serif'],
        'sans': ['Nunito Sans', 'sans-serif', ...defaultTheme.fontFamily.sans],
      },
      boxShadow: {
        'single-inset': 'inset 0px 0px 10px #FFFFFF',
        'double-inset': '0px 0px 5px rgba(0, 0, 0, 0.5), inset 0px 0px 10px #FFFFFF',
        'nft-inset': 'inset 0px 0px 10px rgba(255, 255, 255, 0.25)',
        'btn': '0px 0px 8px #3271D8',
      }
    },
  },
  plugins: [require('daisyui')],
}
